version = 0.1
[dev.deploy.parameters]
stack_name = "app-put-message-slack-dev-stack"
resolve_s3 = true
s3_prefix = "app-put-message-slack/dev"
region = "eu-west-1"
profile = "879381257984_AWS-Sandbox-AdminAccess"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "EnvironmentName=dev",
    "client=mgitservice",
    "SsmParameterSlackToken=/mgitservice/dev/webhook/token",
    "SsmParameterWebhookUrl=/mgitservice/dev/url/webhook"
]
