AWSTemplateFormatVersion: "2010-09-09"
Description: Stack CloudFormation pour la creation dun Topic SNS

Parameters:
  LogGroupName:
    Type: String

  client:
    Type: String
    Description: Nom du client pour le role

  PeriodAlarm:
    Type: String

Resources:
  # L'Alarme CloudWatch
  AbsenceOfLogsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "alarm-logs-breaching-${client}-${LogGroupName}"  # Pattern 
      AlarmDescription: !Sub "Alarme pour la log group:${LogGroupName}"
      MetricName: "IncomingLogEvents"
      Namespace: "AWS/Logs"
      Dimensions:
        - Name: LogGroupName
          Value: !Ref LogGroupName
      Statistic: Sum
      Period: !Ref PeriodAlarm # L'alarme vérifie le total des logs toutes les PeriodAlarm secondes
      EvaluationPeriods: 1
      Threshold: 1.0
      ComparisonOperator: LessThanThreshold
      TreatMissingData: breaching # absence de logs
